#!/bin/bash

# Check that the autogenerated file matches the repo (protect against hand-editing).

set -e

python3 color/make_x11_colors.py > x11_colors.rs
diff color/src/x11_colors.rs x11_colors.rs

rm x11_colors.rs
echo "Autogenerated file matches."
exit 0
